musicEngineMap = {
  "SOUTH_BUTTON_DOWN": "SOUTH_CHORD_ON",
  "SOUTH_BUTTON_UP": "SOUTH_CHORD_OFF",
  "WEST_BUTTON_DOWN": "WEST_CHORD_ON",
  "WEST_BUTTON_UP": "WEST_CHORD_OFF",
  "NORTH_BUTTON_DOWN": "NORTH_CHORD_ON",
  "NORTH_BUTTON_UP": "NORTH_CHORD_OFF",
  "EAST_BUTTON_DOWN": "EAST_CHORD_ON",
  "EAST_BUTTON_UP": "EAST_CHORD_OFF",

  "DPAD_LEFT": "LEFT_SECONDARY_ON",
  "DPAD_RIGHT": "RIGHT_SECONDARY_ON",
  "DPAD_X_OFF": "SECONDARY_OFF",

  "DPAD_UP": "OCTAVE_UP",
  "DPAD_DOWN": "OCTAVE_DOWN",

  "LEFT_STICK_UP": "INCREMENT_BASS_POSITION",
  "LEFT_STICK_DOWN": "DECREMENT_BASS_POSITION",

  "LEFT_STICK_RIGHT": "INCREMENT_VOICE_COUNT",
  "LEFT_STICK_LEFT": "DECREMENT_VOICE_COUNT",

  "RIGHT_STICK_BUTTON_DOWN": "INCREMENT_SETTING",
  "LEFT_STICK_BUTTON_DOWN": "DECREMENT_SETTING",

  "RIGHT_STICK_UP": "INCREMENT_KEY",
  "RIGHT_STICK_DOWN": "DECREMENT_KEY",
  
  "RIGHT_STICK_RIGHT": "INCREMENT_SPREAD",
  "RIGHT_STICK_LEFT": "DECREMENT_SPREAD",

  "RIGHT_BUMPER_DOWN": "RIGHT_MODULATION_ON",
  "RIGHT_BUMPER_UP": "RIGHT_MODULATION_OFF",
  "LEFT_BUMPER_DOWN": "LEFT_MODULATION_ON",
  "LEFT_BUMPER_UP": "LEFT_MODULATION_OFF",

  "RIGHT_TRIGGER_DOWN": "ALTERNATE_ON",
  "RIGHT_TRIGGER_UP": "ALTERNATE_OFF",
  "LEFT_TRIGGER_DOWN": "BASS_ON",
  "LEFT_TRIGGER_UP": "BASS_OFF",

  "LEFT_OPTIONS_DOWN": "TOGGLE_INVERSION_LOCK",
  "RIGHT_OPTIONS_DOWN": "TOGGLE_HOLD",

  "GYRO_PITCH_UPDATE": "UPDATE_INVERSION",
  "GYRO_ROLL_UPDATE": "UPDATE_AFTERTOUCH"
}