from typing import Any, Callable

class MidiOut:
    def __init__(self) -> None: ...
    def get_ports(self) -> list[str]: ...
    def open_port(self, port: int) -> None: ...
    def close_port(self) -> None: ...
    def is_port_open(self) -> bool: ...
    def send_message(self, message: list[int]) -> None: ...
    def delete(self) -> None: ...

class MidiIn:
    def __init__(self) -> None: ...
    def get_ports(self) -> list[str]: ...
    def open_port(self, port: int) -> None: ...
    def close_port(self) -> None: ...
    def is_port_open(self) -> bool: ...
    def set_callback(self, func: Callable[..., Any], data: Any = None) -> None: ...
    def cancel_callback(self) -> None: ...
    def delete(self) -> None: ...
