from controller_coupler.models.control_map import ControlMap

default_control_map = ControlMap(
    name = "default",
    display_name = "Default",
    inversion_mode = "continuous",
    bass_mode = "continuous",
    map = {

        #MAIN BUTTONS
        "SOUTH_BUTTON": ["INTERNAL_SOUTH_CHORD", "UI_SOUTH_BUTTON", "EXTERNAL_SOUTH_CHORD"],
        "WEST_BUTTON": ["INTERNAL_WEST_CHORD", "UI_WEST_BUTTON", "EXTERNAL_WEST_CHORD"],
        "NORTH_BUTTON": ["INTERNAL_NORTH_CHORD", "UI_NORTH_BUTTON", "EXTERNAL_NORTH_CHORD"],
        "EAST_BUTTON": ["INTERNAL_EAST_CHORD", "UI_EAST_BUTTON", "EXTERNAL_EAST_CHORD"],

        #DPAD
        "DPAD_X_LEFT": ["LEFT_SECONDARY", "UI_DPAD_LEFT"],
        "DPAD_X_RIGHT": ["RIGHT_SECONDARY", "UI_DPAD_RIGHT"],

        "DPAD_Y": ["INTERNAL_OCTAVE", "EXTERNAL_OCTAVE"],
        "DPAD_Y_UP": ["UI_DPAD_UP"],
        "DPAD_Y_DOWN": ["UI_DPAD_DOWN"],

        #LEFT STICK
        "LEFT_STICK_Y_POLAR": ["INTERNAL_OCTAVE", "EXTERNAL_OCTAVE"],
        "LEFT_STICK_X_POLAR": ["INTERNAL_VOICE_COUNT", "EXTERNAL_VOICE_COUNT"],

        "LEFT_STICK_Y_DOWN": ["UI_LEFT_STICK_DOWN"],
        "LEFT_STICK_Y_UP": ["UI_LEFT_STICK_UP"],
        "LEFT_STICK_X_LEFT": ["UI_LEFT_STICK_LEFT"],
        "LEFT_STICK_X_RIGHT": ["UI_LEFT_STICK_RIGHT"],

        #STICK BUTTONS
        "RIGHT_STICK_BUTTON": ["INCREMENT_SETTING", "UI_RIGHT_STICK_BUTTON"],
        "LEFT_STICK_BUTTON": ["DECREMENT_SETTING", "UI_LEFT_STICK_BUTTON"],

        #RIGHT STICK
        "RIGHT_STICK_Y_POLAR": ["INTERNAL_KEY", "EXTERNAL_KEY"],
        "RIGHT_STICK_X_POLAR": ["INTERNAL_SPREAD", "EXTERNAL_SPREAD"],

        "RIGHT_STICK_Y_DOWN": ["UI_RIGHT_STICK_DOWN"],
        "RIGHT_STICK_Y_UP": ["UI_RIGHT_STICK_UP"],
        "RIGHT_STICK_X_LEFT": ["UI_RIGHT_STICK_LEFT"],
        "RIGHT_STICK_X_RIGHT": ["UI_RIGHT_STICK_RIGHT"],

        #BUMPERS
        "RIGHT_BUMPER": ["RIGHT_MODULATION", "UI_RIGHT_BUMPER"],
        "LEFT_BUMPER": ["LEFT_MODULATION", "UI_LEFT_BUMPER"],

        #TRIGGERS
        "RIGHT_TRIGGER": ["ALTERNATE", "UI_RIGHT_TRIGGER"],
        "LEFT_TRIGGER": ["INTERNAL_BASS", "UI_LEFT_TRIGGER", "EXTERNAL_BASS"],

        #OPTIONS
        "LEFT_OPTION": ["INTERNAL_INVERSION_LOCK", "EXTERNAL_INVERSION_LOCK", "UI_LEFT_OPTION"],
        "RIGHT_OPTION": ["INTERNAL_HOLD", "EXTERNAL_HOLD", "UI_RIGHT_OPTION"],

        #TOUCHPAD
        "TOUCHPAD_X": ["INTERNAL_BASS_POSITION", "UI_TOUCHPAD_X", "UI_BASS_THUMB", "EXTERNAL_BASS_POSITION"],
        "TOUCHPAD_Y": ["UI_TOUCHPAD_Y"],

        #UI
        "START_BUTTON": ["MENU"],

        #GYROSCOPE
        "GYRO_PITCH": ["INTERNAL_INVERSION", "EXTERNAL_INVERSION", "UI_INVERSION_THUMB"],
        "GYRO_ROLL": ["AFTERTOUCH"],
  }
)
